// This is an autogenerated Layer Switcher enum file. You can move it or rename it, but do not edit!
namespace HumboldtForum.Main
{
    public enum LayerName
    {
        Init,
        NavigatorIntro,
        TurtleIntro,
        Start,
        SunAssignment,
        SailWest,
        StarsAssignment,
        SailSouth,
        CloudsAssignment,
        SailToBirds,
        BirdsAssignment,
        SailToIsland,
        PartyIsland
    }
}