// This is an autogenerated Layer Switcher enum file. You can move it or rename it, but do not edit!
namespace HumboldtForum.Audio.Sail
{
    public enum LayerName
    {
        Flapping,
        Slow,
        Fast
    }
}